### ISSUE TITLE
TestIntegrationConnConcurrentSerializeExecute fails to get family "acpi_event": netlink receive: no such file or directory

### ISSUE THREAD

**Issue by bdrung** [mdlayher/genetlink#7]
I packaged genetlink for Debian: [golang-github-mdlayher-genetlink](https://tracker.debian.org/pkg/golang-github-mdlayher-genetlink). The autopkgtest fail to run the `TestIntegrationConnConcurrentSerializeExecute` test:

```
=== RUN   TestIntegrationConnConcurrentSerializeExecute
panic: failed to get family "acpi_event": netlink receive: no such file or directory

goroutine 47 [running]:
genetlink_test.panicf(...)
	conn_linux_integration_test.go:180
genetlink_test.TestIntegrationConnConcurrentSerializeExecute.func1(0x7d0, {0x5ba28b, 0xa})
	conn_linux_integration_test.go:150 +0x2a9
genetlink_test.TestIntegrationConnConcurrentSerializeExecute.func2({0x5ba28b, 0xc0000377b8})
	conn_linux_integration_test.go:174 +0x6f
created by genetlink_test.TestIntegrationConnConcurrentSerializeExecute
	conn_linux_integration_test.go:172 +0x268
FAIL	genetlink	1.215s
```

Please run the integration test with a mocket netlink or check for system support.

Full test log: https://ci.debian.net/data/autopkgtest/testing/amd64/g/golang-github-mdlayher-genetlink/18330278/log.gz

**Comment by mdlayher** [comment]
Fixed by https://github.com/mdlayher/genetlink/commit/30b6af362ad2440c92f7efd0dc62d3685093256a.
